# Porta do servidor
server.port=8080

# Nome da aplicação Spring
spring.application.name=servico-pedidos

# Configuração do Spring Cloud Stream para o RabbitMQ
# spring.cloud.stream.function.definition=publicarNovoPedido

spring.cloud.stream.bindings.publicarNovoPedido-out-0.destination=pedidos-exchange

# Define o binding de saída (producer)
# O nome 'publicarNovoPedido-out-0' é gerado pelo Spring Cloud Stream a partir da definição da função.
# 'pedidos-exchange' é o nome da exchange (tópico) no RabbitMQ.
spring.cloud.stream.bindings.publicarNovoPedido-out-0.destination=pedidos-exchange

# Configuração do RabbitMQ Broker
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest