# Porta do servidor
server.port=8081

# Nome da aplicação Spring
spring.application.name=servico-faturamento

# Configuração do Spring Cloud Stream
spring.cloud.stream.function.definition=processarPedidoFaturamento

# Define o binding de entrada (consumer) e o grupo de consumidores
# 'pedidos-exchange' é o tópico do qual estamos consumindo.
# 'faturamento-group' é o grupo de consumidores, garantindo que a mensagem seja lida apenas uma vez pelo grupo.
spring.cloud.stream.bindings.processarPedidoFaturamento-in-0.destination=pedidos-exchange
spring.cloud.stream.bindings.processarPedidoFaturamento-in-0.group=faturamento-group

# Configuração do RabbitMQ Broker
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest